onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - optipng-bin
  - pngquant-bin
  - prisma
  - sharp
  - unrs-resolver
  - zopflipng-bin
